version: '3.1'

services:
  webserver:
    image: nginx:alpine
    working_dir: /var/www/api
    container_name: webserver
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/api
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    image: falcon4ik007/php8.1-fpm:latest
    working_dir: /var/www/api
    container_name: php-fpm
    volumes:
      - .:/var/www/api